/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: ChangedFilter.jgn
 * Variable definitions: ChangedFilter.json
 * Label used: Boolean
 */
package arachne.lib.pipeline.filters;

import arachne.lib.function.BooleanPredicate;

public class ChangedBooleanFilter implements BooleanPredicate
{
	protected boolean isFirst;
	protected boolean lastValue;

	public ChangedBooleanFilter() {
		this.isFirst = true;
	}

	@Override
	public boolean test(boolean value) {
		boolean result = value != lastValue;
		lastValue = value;

		if(isFirst) {
			isFirst = false;
			return true;
		}

		return result;
	}
}
