/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: ChangedFilter.jgn
 * Variable definitions: ChangedFilter.json
 * Label used: Generic
 */
package arachne.lib.pipeline.filters;

import java.util.function.Predicate;

public class ChangedFilter<T> implements Predicate<T>
{
	protected boolean isFirst;
	protected T lastValue;

	public ChangedFilter() {
		this.isFirst = true;
	}

	@Override
	public boolean test(T value) {
		boolean result = !value.equals(lastValue);
		lastValue = value;

		if(isFirst) {
			isFirst = false;
			return true;
		}

		return result;
	}
}
