/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: ChangedFilter.jgn
 * Variable definitions: ChangedFilter.json
 * Label used: Double
 */
package arachne.lib.pipeline.filters;

import java.util.function.DoublePredicate;

public class ChangedDoubleFilter implements DoublePredicate
{
	protected boolean isFirst;
	protected double lastValue;

	public ChangedDoubleFilter() {
		this.isFirst = true;
	}

	@Override
	public boolean test(double value) {
		boolean result = value != lastValue;
		lastValue = value;

		if(isFirst) {
			isFirst = false;
			return true;
		}

		return result;
	}
}
