/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: ScheduledSource.jgn
 * Variable definitions: ScheduledSource.json
 * Label used: Double
 */
package arachne.lib.scheduler;

import arachne.lib.io.GettableDouble;
import arachne.lib.io.SettableDouble;
import arachne.lib.pipeline.DoubleListener;
import arachne.lib.pipeline.DoublePipe;
import arachne.lib.pipeline.DoubleSource;
import arachne.lib.pipeline.filters.ChangedDoubleFilter;

public class ScheduledDoubleSource implements Schedulable, DoubleSource
{
	protected final GettableDouble target;
	protected final DoublePipe pipe;

	public ScheduledDoubleSource(double initialValue, GettableDouble target) {
		this.target = target;

		this.pipe = new DoublePipe(initialValue);
		this.pipe.setFilter(new ChangedDoubleFilter());
	}

	public void run() {
		pipe.accept(target.get());
	}

	@Override
	public double get() {
		return pipe.get();
	}

	@Override
	public <SettableT extends SettableDouble> SettableT attach(SettableT settable) {
		return pipe.attach(settable);
	}

	@Override
	public <ListenerT extends DoubleListener> ListenerT attachListener(ListenerT listener) {
		return pipe.attachListener(listener);
	}

	@Override
	public boolean detach(SettableDouble settable) {
		return pipe.detach(settable);
	}

	@Override
	public boolean detachListener(DoubleListener listener) {
		return pipe.detachListener(listener);
	}

	@Override
	public void detachAll() {
		pipe.detachAll();
	}
}
