/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: ScheduledSource.jgn
 * Variable definitions: ScheduledSource.json
 * Label used: Generic
 */
package arachne.lib.scheduler;

import arachne.lib.io.Gettable;
import arachne.lib.io.Settable;
import arachne.lib.pipeline.Listener;
import arachne.lib.pipeline.Pipe;
import arachne.lib.pipeline.Source;
import arachne.lib.pipeline.filters.ChangedFilter;

public class ScheduledSource<T> implements Schedulable, Source<T>
{
	protected final Gettable<T> target;
	protected final Pipe<T> pipe;

	public ScheduledSource(T initialValue, Gettable<T> target) {
		this.target = target;

		this.pipe = new Pipe<T>(initialValue);
		this.pipe.setFilter(new ChangedFilter<T>());
	}

	public void run() {
		pipe.accept(target.get());
	}

	@Override
	public T get() {
		return pipe.get();
	}

	@Override
	public <SettableT extends Settable<T>> SettableT attach(SettableT settable) {
		return pipe.attach(settable);
	}

	@Override
	public <ListenerT extends Listener<T>> ListenerT attachListener(ListenerT listener) {
		return pipe.attachListener(listener);
	}

	@Override
	public boolean detach(Settable<T> settable) {
		return pipe.detach(settable);
	}

	@Override
	public boolean detachListener(Listener<T> listener) {
		return pipe.detachListener(listener);
	}

	@Override
	public void detachAll() {
		pipe.detachAll();
	}
}
