/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Listener.jgn
 * Variable definitions: Listener.json
 * Label used: Boolean
 */
package arachne.lib.pipeline;

@FunctionalInterface
public interface BooleanListener
{
	void onChange(boolean oldValue, boolean newValue);
}
