/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Listener.jgn
 * Variable definitions: Listener.json
 * Label used: Double
 */
package arachne.lib.pipeline;

@FunctionalInterface
public interface DoubleListener
{
	void onChange(double oldValue, double newValue);
}
