/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Listener.jgn
 * Variable definitions: Listener.json
 * Label used: Generic
 */
package arachne.lib.pipeline;

@FunctionalInterface
public interface Listener<T>
{
	void onChange(T oldValue, T newValue);
}
