/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Input.jgn
 * Variable definitions: Input.json
 * Label used: GettableBoolean
 */
package arachne.lib.io.sensors;

import arachne.lib.io.GettableBoolean;
import arachne.lib.io.sensors.Input;
import arachne.lib.logging.ArachneLogger;

public final class GettableBooleanInput implements Input<GettableBoolean>, GettableBoolean {
	protected GettableBoolean sensor;

	public void populate(GettableBoolean sensor) {
		this.sensor = sensor;
	}

	@Override
	public boolean get() {
		if(sensor != null) return sensor.get();

		ArachneLogger.getInstance().error("Tried to get GettableBooleanInput wrapper with no contained sensor, returning false");
		return false;
	}
}
