/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Input.jgn
 * Variable definitions: Input.json
 * Label used: GettableDouble
 */
package arachne.lib.io.sensors;

import arachne.lib.io.GettableDouble;
import arachne.lib.io.sensors.Input;
import arachne.lib.logging.ArachneLogger;

public final class GettableDoubleInput implements Input<GettableDouble>, GettableDouble {
	protected GettableDouble sensor;

	public void populate(GettableDouble sensor) {
		this.sensor = sensor;
	}

	@Override
	public double get() {
		if(sensor != null) return sensor.get();

		ArachneLogger.getInstance().error("Tried to get GettableDoubleInput wrapper with no contained sensor, returning 0");
		return 0;
	}
}
