/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Input.jgn
 * Variable definitions: Input.json
 * Label used: GettableGeneric
 */
package arachne.lib.io.sensors;

import arachne.lib.io.Gettable;
import arachne.lib.io.sensors.Input;
import arachne.lib.logging.ArachneLogger;

public final class GettableInput<T> implements Input<Gettable<T>>, Gettable<T> {
	protected Gettable<T> sensor;

	public void populate(Gettable<T> sensor) {
		this.sensor = sensor;
	}

	@Override
	public T get() {
		if(sensor != null) return sensor.get();

		ArachneLogger.getInstance().error("Tried to get GettableInput wrapper with no contained sensor, returning null");
		return null;
	}
}
