/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Input.jgn
 * Variable definitions: Input.json
 * Label used: Resettable
 */
package arachne.lib.io.sensors;

import arachne.lib.io.sensors.Input;
import arachne.lib.logging.ArachneLogger;

public final class ResettableDoubleInput implements Input<ResettableDoubleSensor>, ResettableDoubleSensor {
	protected ResettableDoubleSensor sensor;

	public void populate(ResettableDoubleSensor sensor) {
		this.sensor = sensor;
	}

	@Override
	public double get() {
		if(sensor != null) return sensor.get();

		ArachneLogger.getInstance().error("Tried to get ResettableDoubleInput wrapper with no contained sensor, returning 0");
		return 0;
	}

	@Override
	public void reset() {
		if(sensor != null) sensor.reset();
		else ArachneLogger.getInstance().error("Tried to reset ResettableDoubleInput wrapper with no contained sensor");
	}
}
