/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Input.jgn
 * Variable definitions: Input.json
 * Label used: Settable
 */
package arachne.lib.io.sensors;

import arachne.lib.io.sensors.Input;
import arachne.lib.logging.ArachneLogger;

public final class SettableDoubleInput implements Input<SettableDoubleSensor>, SettableDoubleSensor {
	protected SettableDoubleSensor sensor;

	public void populate(SettableDoubleSensor sensor) {
		this.sensor = sensor;
	}

	@Override
	public double get() {
		if(sensor != null) return sensor.get();

		ArachneLogger.getInstance().error("Tried to get SettableDoubleInput wrapper with no contained sensor, returning 0");
		return 0;
	}

	@Override
	public void accept(double value) {
		if(sensor != null) sensor.accept(value);
		else ArachneLogger.getInstance().error("Tried to set SettableDoubleInput wrapper with no contained sensor");
	}

	@Override
	public void reset() {
		if(sensor != null) sensor.reset();
		else ArachneLogger.getInstance().error("Tried to reset SettableDoubleInput wrapper with no contained sensor");
	}
}
