/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Gettable.jgn
 * Variable definitions: Gettable.json
 * Label used: Double
 */
package arachne.lib.io;

import java.util.function.DoublePredicate;
import java.util.function.DoubleSupplier;
import java.util.function.DoubleUnaryOperator;

@FunctionalInterface
public interface GettableDouble extends DoubleSupplier
{
	double get();

	@Override
	default double getAsDouble() {
		return get();
	}

	default GettableBoolean is(double target) {
		return () -> get() == target;
	}

	default GettableBoolean is(DoublePredicate predicate) {
		return () -> predicate.test(get());
	}

	default GettableDouble change(DoubleUnaryOperator modifier) {
		return () -> modifier.applyAsDouble(get());
	}

	public static GettableDouble create(GettableDouble lambda) {
		return lambda;
	}
}
