/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Gettable.jgn
 * Variable definitions: Gettable.json
 * Label used: Generic
 */
package arachne.lib.io;

import java.util.function.Predicate;
import java.util.function.Supplier;
import java.util.function.UnaryOperator;

@FunctionalInterface
public interface Gettable<T> extends Supplier<T>
{
	default GettableBoolean is(T target) {
		return () -> get() == target;
	}

	default GettableBoolean is(Predicate<T> predicate) {
		return () -> predicate.test(get());
	}

	default Gettable<T> change(UnaryOperator<T> modifier) {
		return () -> modifier.apply(get());
	}

	public static <T> Gettable<T> create(Gettable<T> lambda) {
		return lambda;
	}
}
