/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Settable.jgn
 * Variable definitions: Settable.json
 * Label used: Generic
 */
package arachne.lib.io;

import java.util.function.Consumer;

@FunctionalInterface
public interface Settable<T> extends Consumer<T>
{
	public static <T> Settable<T> create(Settable<T> lambda) {
		return lambda;
	}
}
