/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Settable.jgn
 * Variable definitions: Settable.json
 * Label used: Boolean
 */
package arachne.lib.io;

import arachne.lib.function.BooleanConsumer;

@FunctionalInterface
public interface SettableBoolean extends BooleanConsumer
{
	public static SettableBoolean create(SettableBoolean lambda) {
		return lambda;
	}
}
