/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Settable.jgn
 * Variable definitions: Settable.json
 * Label used: Double
 */
package arachne.lib.io;

import java.util.function.DoubleConsumer;

@FunctionalInterface
public interface SettableDouble extends DoubleConsumer
{
	public static SettableDouble create(SettableDouble lambda) {
		return lambda;
	}
}
