/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Translator.jgn
 * Variable definitions: Translator.json
 * Label used: BooleanToDouble
 */
package arachne.lib.pipeline.translators;

import arachne.lib.function.BooleanToDoubleFunction;
import arachne.lib.io.SettableBoolean;
import arachne.lib.io.SettableDouble;
import arachne.lib.pipeline.DoubleListener;
import arachne.lib.pipeline.DoubleSource;
import arachne.lib.pipeline.DoublePipe;

public class BooleanToDoubleTranslator implements SettableBoolean, DoubleSource
{
	protected final DoublePipe pipe;
	protected final BooleanToDoubleFunction translation;

	public BooleanToDoubleTranslator(boolean initialInputValue, BooleanToDoubleFunction translation) {
		this.pipe = new DoublePipe(translation.apply(initialInputValue));
		this.translation = translation;
	}

	@Override
	public void accept(boolean value) {
		pipe.accept(translation.apply(value));
	}

	@Override
	public double get() {
		return pipe.get();
	}

	@Override
	public <SettableT extends SettableDouble> SettableT attach(SettableT settable) {
		return pipe.attach(settable);
	}

	@Override
	public <ListenerT extends DoubleListener> ListenerT attachListener(ListenerT listener) {
		return pipe.attachListener(listener);
	}

	@Override
	public boolean detach(SettableDouble settable) {
		return pipe.detach(settable);
	}

	@Override
	public boolean detachListener(DoubleListener listener) {
		return pipe.detachListener(listener);
	}

	@Override
	public void detachAll() {
		pipe.detachAll();
	}
}
