/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: Translator.jgn
 * Variable definitions: Translator.json
 * Label used: GenericToGeneric
 */
package arachne.lib.pipeline.translators;

import java.util.function.Function;

import arachne.lib.io.Settable;
import arachne.lib.pipeline.Listener;
import arachne.lib.pipeline.Pipe;
import arachne.lib.pipeline.Source;

public class Translator<InputT, OutputT> implements Settable<InputT>, Source<OutputT>
{
	protected final Pipe<OutputT> pipe;
	protected final Function<InputT, OutputT> translation;

	public Translator(InputT initialInputValue, Function<InputT, OutputT> translation) {
		this.pipe = new Pipe<OutputT>(translation.apply(initialInputValue));
		this.translation = translation;
	}

	@Override
	public void accept(InputT value) {
		pipe.accept(translation.apply(value));
	}

	@Override
	public OutputT get() {
		return pipe.get();
	}

	@Override
	public <SettableT extends Settable<OutputT>> SettableT attach(SettableT settable) {
		return pipe.attach(settable);
	}

	@Override
	public <ListenerT extends Listener<OutputT>> ListenerT attachListener(ListenerT listener) {
		return pipe.attachListener(listener);
	}

	@Override
	public boolean detach(Settable<OutputT> settable) {
		return pipe.detach(settable);
	}

	@Override
	public boolean detachListener(Listener<OutputT> listener) {
		return pipe.detachListener(listener);
	}

	@Override
	public void detachAll() {
		pipe.detachAll();
	}
}
