/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: FlaggedValue.jgn
 * Variable definitions: FlaggedValue.json
 * Label used: Double
 */
package arachne.lib.immutables;

public class FlaggedDoubleValue
{
	protected double value;
	protected boolean flag;

	public FlaggedDoubleValue(double value, boolean flag) {
		this.value = value;
		this.flag = flag;
	}

	public double getValue() {
		return value;
	}

	public boolean getFlag() {
		return flag;
	}
}
