/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: FlaggedValue.jgn
 * Variable definitions: FlaggedValue.json
 * Label used: Generic
 */
package arachne.lib.immutables;

public class FlaggedValue<T>
{
	protected T value;
	protected boolean flag;

	public FlaggedValue(T value, boolean flag) {
		this.value = value;
		this.flag = flag;
	}

	public T getValue() {
		return value;
	}

	public boolean getFlag() {
		return flag;
	}
}
