/*
 * This file was auto-generated by Arachne's Template Manager.
 * Edits made to this file will be overridden on regeneration.
 *
 * Template file: FlaggedValue.jgn
 * Variable definitions: FlaggedValue.json
 * Label used: Boolean
 */
package arachne.lib.immutables;

public class FlaggedBooleanValue
{
	protected boolean value;
	protected boolean flag;

	public FlaggedBooleanValue(boolean value, boolean flag) {
		this.value = value;
		this.flag = flag;
	}

	public boolean getValue() {
		return value;
	}

	public boolean getFlag() {
		return flag;
	}
}
